version: '3.8'

services:
  user-microservice:
    image: user-microservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_database
      MYSQL_USER: user_admin
      MYSQL_PASSWORD: user_password_test
    ports:
      - "3306:3306"